language: c

sudo: required

dist: trusty

os:
- linux
- osx

#install:
#- python setup.py -q install

script:
- >-
    tests/run.sh nocompile
        tests/cid_vcs_test.py
        tests/cid_install_test.py
        tests/cid_buildtool_test.py
        tests/cid_runcmd_test.py
        tests/cid_initcmd_test.py
        tests/cid_misc_test.py
        tests/cid_deploy_test.py
        tests/cid_service_test.py
# allow failures, as is quite depends on changing app versions
- >-
    [ "${TRAVIS_OS_NAME}" = "linux" ] &&
    tests/run.sh rmshost &&
    tests/run.sh
        tests/cid_realapp_test.py
        tests/cid_rms_test.py
        tests/cid_migrate_test.py
    || true
